---
AWSTemplateFormatVersion: 2010-09-09


Description: >
  This template shows how to use AWS Secret Manager.
Parameters:

  
  AuthSecretValue:
    Type: String
    NoEcho: true
    Description: >
      Value for the AUTH_SECRET variable.
  
  AuthCodesSecretValue:
    Type: String
    NoEcho: true
    Description: >
      Value for the AUTH_CODES_SECRET variable.
  
  RecaptchaSecretValue:
    Type: String
    NoEcho: true
    Description: >
      Value for the RECAPTCHA variable.

  Environment:
    Type: String
    Default: pre
    Description: pre | pro

Resources:
  ServerlessDeployments:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: 
        !Join
          - ''
          - - 'qs-super-serverless-deployments-'
            - !Ref Environment 

  AuthSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name:
        !Join
        - ''
        - - 'qs-super-api-'
          - !Ref Environment
      Description: Secret used in a backend API
      SecretString: 
        !Join
          - ''
          - - "{\"AUTH_SECRET\":\""
            - !Ref AuthSecretValue
            - "\",\"AUTH_CODES_SECRET\":\""
            - !Ref AuthCodesSecretValue
            - "\",\"RECAPTCHA\":\""
            - !Ref RecaptchaSecretValue
            - "\"}"

